# This file was generated by GoReleaser. DO NOT EDIT.
cask "vduck" do
  version "1.2.1"

  on_macos do
    on_arm do
      sha256 "73cc985071e06fc9781b3df3e03b645210bfb9aa0af7033413e5f1d25b755c1d"
      url "https://github.com/akhenakh/vduck/releases/download/v#{version}/vduck_Darwin_arm64.tar.gz",
        verified: "github.com/akhenakh/vduck"
    end
  end

  on_linux do
    on_intel do
      sha256 "c8c0aadd49f4caeb048c20694091f41b67dd2c806b36679f918e22a27dcca507"
      url "https://github.com/akhenakh/vduck/releases/download/v#{version}/vduck_Linux_x86_64.tar.gz",
        verified: "github.com/akhenakh/vduck"
    end
    on_arm do
      sha256 "db01bf9309aaaf379c6a8888c4d5f39f6c12d74fd7834f6f361a281f5d497678"
      url "https://github.com/akhenakh/vduck/releases/download/v#{version}/vduck_Linux_arm64.tar.gz",
        verified: "github.com/akhenakh/vduck"
    end
  end

  name "vduck"
  desc "A simple terminal UI for DuckDB"
  homepage "https://github.com/akhenakh/vduck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vduck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vduck"]
    end
  end

  # No zap stanza required

end
