# This file was generated by GoReleaser. DO NOT EDIT.
cask "vduck" do
  version "1.2.2"

  on_macos do
    on_arm do
      sha256 "6448cf13e8e070c24ac0050373b4459403de433ddb95207ae2fe963e10414ae6"
      url "https://github.com/akhenakh/vduck/releases/download/v#{version}/vduck_Darwin_arm64.tar.gz",
        verified: "github.com/akhenakh/vduck"
    end
  end

  on_linux do
    on_intel do
      sha256 "af971fb4a9d5f2c42aa2203114517f970db538fabb2f423eb22fa4ef9998a1ed"
      url "https://github.com/akhenakh/vduck/releases/download/v#{version}/vduck_Linux_x86_64.tar.gz",
        verified: "github.com/akhenakh/vduck"
    end
    on_arm do
      sha256 "ef0718a73713e6e158ae8323ee30cfff7ddd7517bef232ccea5f14e65e59de98"
      url "https://github.com/akhenakh/vduck/releases/download/v#{version}/vduck_Linux_arm64.tar.gz",
        verified: "github.com/akhenakh/vduck"
    end
  end

  name "vduck"
  desc "A simple terminal UI for DuckDB"
  homepage "https://github.com/akhenakh/vduck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vduck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vduck"]
    end
  end

  # No zap stanza required

end
