# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vduck < Formula
  desc "Simple terminal UI for DuckDB"
  homepage "https://github.com/akhenakh/vduck"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/akhenakh/vduck/releases/download/v1.2.1/vduck_Darwin_arm64.tar.gz"
      sha256 "73cc985071e06fc9781b3df3e03b645210bfb9aa0af7033413e5f1d25b755c1d"

      define_method(:install) do
        bin.install "vduck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akhenakh/vduck/releases/download/v1.2.1/vduck_Linux_x86_64.tar.gz"
      sha256 "c8c0aadd49f4caeb048c20694091f41b67dd2c806b36679f918e22a27dcca507"
      define_method(:install) do
        bin.install "vduck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akhenakh/vduck/releases/download/v1.2.1/vduck_Linux_arm64.tar.gz"
      sha256 "db01bf9309aaaf379c6a8888c4d5f39f6c12d74fd7834f6f361a281f5d497678"
      define_method(:install) do
        bin.install "vduck"
      end
    end
  end
end
